[package]
name = "reth-proofs"
version = "0.1.0"
edition = "2024"

[dependencies]

# NOTE: Version of alloy/revm/reth crates is based on reth v1.4.8:
# - https://github.com/paradigmxyz/reth/blob/v1.4.8/Cargo.toml

# alloy
alloy-provider = { version = "1.0.9", default-features = false, features = ["reqwest", "debug-api"] }
alloy-rpc-types-debug = { version = "1.0.9", default-features = false }
alloy-rpc-types-eth = { version = "1.0.9", default-features = false }

# Asynchronous runtime.
tokio = { version = "1.45.1", default-features = false }

# Error handling.
thiserror = { version = "2.0.12", default-features = false }
