[workspace]
members = [
  "core",
  "zkvm/sp1-guest",
  "zkvm/sp1-host",
  "prototype",
]
resolver = "3"

[workspace.dependencies]
reth-proofs-core = { path = "./core" }

# `sha3-keccak` is required to use SP1 precompile.
alloy-primitives = { version = "1.1.0", features = ["sha3-keccak"] }

[patch.crates-io]
# SP1 precompiles.
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha3-0.10.8-sp1-4.0.0" }
