[package]
name = "reth-proofs-gevulot"
version = "0.1.0"
edition = "2024"

[dependencies]
# Asynchronous runtime.
tokio = { workspace = true }

# CLI parsing.
clap = { version = "4.5.40", features = ["derive", "env"] }

# Error handling.
eyre = { version = "0.6.12", default-features = false }

# zkVM.
sp1-sdk = { workspace = true }

[build-dependencies]
# zkVM.
sp1-build = { workspace = true }
