[package]
name = "reth-proofs-core"
version = "0.1.0"
edition = "2024"

[dependencies]

# NOTE: Version of alloy/revm/reth crates is based on reth v1.4.8:
# - https://github.com/paradigmxyz/reth/blob/v1.4.8/Cargo.toml

# reth
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.4.8", default-features = false }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.4.8", default-features = false, features = ["evm"] }
