[package]
name = "reth-proofs-zkvm-common-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# Reth Proofs
reth-proofs = { workspace = true }
reth-proofs-core = { workspace = true }

# Serialization.
bincode = { workspace = true }
