[package]
version = "0.1.0"
name = "reth-proofs-zkvm-sp1-host"
edition = "2024"

[dependencies]
sp1-sdk = { version = "5.0.6", default-features = false, features = ["profiling"] }

[build-dependencies]
sp1-build = { version = "5.0.5", default-features = false }
